// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mcmc_tessellation
Rcpp::List mcmc_tessellation(const arma::mat& distance_matrix, Rcpp::List likelihood_params, Rcpp::List prior_params, Rcpp::List algo_params);
RcppExport SEXP _HPCVoronoiClust_mcmc_tessellation(SEXP distance_matrixSEXP, SEXP likelihood_paramsSEXP, SEXP prior_paramsSEXP, SEXP algo_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type distance_matrix(distance_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type likelihood_params(likelihood_paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type prior_params(prior_paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type algo_params(algo_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_tessellation(distance_matrix, likelihood_params, prior_params, algo_params));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_PY
Rcpp::List mcmc_PY(const arma::mat& distance_matrix, Rcpp::List likelihood_params, Rcpp::List prior_params, Rcpp::List algo_params);
RcppExport SEXP _HPCVoronoiClust_mcmc_PY(SEXP distance_matrixSEXP, SEXP likelihood_paramsSEXP, SEXP prior_paramsSEXP, SEXP algo_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type distance_matrix(distance_matrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type likelihood_params(likelihood_paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type prior_params(prior_paramsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type algo_params(algo_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_PY(distance_matrix, likelihood_params, prior_params, algo_params));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HPCVoronoiClust_mcmc_tessellation", (DL_FUNC) &_HPCVoronoiClust_mcmc_tessellation, 4},
    {"_HPCVoronoiClust_mcmc_PY", (DL_FUNC) &_HPCVoronoiClust_mcmc_PY, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_HPCVoronoiClust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
