# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_log_prob_D_rcpp_list <- function(D, z, params) {
    .Call(`_VoronoiClust_get_log_prob_D_rcpp_list`, D, z, params)
}

get_log_prob_D_rcpp <- function(D, z, params) {
    .Call(`_VoronoiClust_get_log_prob_D_rcpp`, D, z, params)
}

get_log_prob_partition_rcpp <- function(z, M, theta) {
    .Call(`_VoronoiClust_get_log_prob_partition_rcpp`, z, M, theta)
}

check_same_partition_rcpp <- function(c1, c2) {
    .Call(`_VoronoiClust_check_same_partition_rcpp`, c1, c2)
}

update_gammas_rcpp <- function(z1, z2, M, theta, gamma_d, alpha_d) {
    .Call(`_VoronoiClust_update_gammas_rcpp`, z1, z2, M, theta, gamma_d, alpha_d)
}

get_log_prob_allocations_comp_check_rcpp <- function(z1, z2, gamma_d, i, M, theta, D, params) {
    .Call(`_VoronoiClust_get_log_prob_allocations_comp_check_rcpp`, z1, z2, gamma_d, i, M, theta, D, params)
}

get_log_prob_allocations_rcpp <- function(z, i, M, theta, D, params) {
    .Call(`_VoronoiClust_get_log_prob_allocations_rcpp`, z, i, M, theta, D, params)
}

get_log_prob_allocations_marginal_rcpp <- function(z, i, M, theta, D, params) {
    .Call(`_VoronoiClust_get_log_prob_allocations_marginal_rcpp`, z, i, M, theta, D, params)
}

telescopic_dependence_rcpp <- function(z1, z2) {
    .Call(`_VoronoiClust_telescopic_dependence_rcpp`, z1, z2)
}

updateOracle_rcpp <- function(oracle_posterior, oracle_coclustering, pnts1, clust_centres1, Cov1, tempprobs) {
    .Call(`_VoronoiClust_updateOracle_rcpp`, oracle_posterior, oracle_coclustering, pnts1, clust_centres1, Cov1, tempprobs)
}

sampleDistances_rcpp <- function(z1, hyperparams_lik) {
    .Call(`_VoronoiClust_sampleDistances_rcpp`, z1, hyperparams_lik)
}

update_z1_rcpp <- function(z1, z2, gamma_d, M, theta, D1, params) {
    .Call(`_VoronoiClust_update_z1_rcpp`, z1, z2, gamma_d, M, theta, D1, params)
}

update_z2_rcpp <- function(z1, z2, gamma_d, M, theta, D2, params) {
    .Call(`_VoronoiClust_update_z2_rcpp`, z1, z2, gamma_d, M, theta, D2, params)
}

get_log_prob_D_tesselation_2_rcpp <- function(D, z, centers, repulsion, params) {
    .Call(`_VoronoiClust_get_log_prob_D_tesselation_2_rcpp`, D, z, centers, repulsion, params)
}

get_log_prob_D_tesselation_rcpp <- function(D, z, centers, repulsion, params) {
    .Call(`_VoronoiClust_get_log_prob_D_tesselation_rcpp`, D, z, centers, repulsion, params)
}

