# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run Reversible Jump MCMC for Voronoi Tessellation
#'
#' @export
mcmc_tessellation <- function(distance_matrix, likelihood_params, prior_params, algo_params) {
    .Call(`_HPCVoronoiClust_mcmc_tessellation`, distance_matrix, likelihood_params, prior_params, algo_params)
}

#' Run Split-Merge MCMC for Pitman-Yor Process Mixture Model
#'
#' @export
mcmc_PY <- function(distance_matrix, likelihood_params, prior_params, algo_params) {
    .Call(`_HPCVoronoiClust_mcmc_PY`, distance_matrix, likelihood_params, prior_params, algo_params)
}

#' Run Reversible Jump MCMC for Multi-View Voronoi Tessellation
#'
#' @export
mcmc_multiview_tessellation <- function(distance_matrices, likelihood_params, prior_params, algo_params) {
    .Call(`_HPCVoronoiClust_mcmc_multiview_tessellation`, distance_matrices, likelihood_params, prior_params, algo_params)
}

